// <auto-generated />
namespace TWRDataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class widen_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(widen_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201307271908160_widen_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
