// <auto-generated />
namespace TWRDataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class widen_tables_update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(widen_tables_update));
        
        string IMigrationMetadata.Id
        {
            get { return "201307271923587_widen_tables_update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
